language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install nose
#- pip install tox tox-travis
script:
- python setup.py install
- nosetests -vdx tests/ --with-coverage --cover-package=oct
after_success:
  - pip install coveralls
  - coverage combine
  - coveralls
